config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  resource :user, only: [:new, :create, :show]

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

	def login?
		if current_user.nil?
			redirect_to login_path, alert: "You have to login"
		end
	end

	def already_login?
		unless current_user.nil?
			redirect_to user_path, notice: "You a already logged in"
		end
	end

	def current_user
		if session[:user_id]
			current_user ||= User.find(session[:user_id])
		end
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path, notice: "ログイン完了"
    else
      flash.now[:alert] = "メールもしくはパスワードが違います"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "ログアウト完了"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
     user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path, notice:"登録完了"
    else
      render 'new'
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>Hello!</h1>

<%= link_to "サインアップ",new_user_path %>
<%= link_to "ログイン", login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <div class="conteiner">
      <%= yield %>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= form_with model: @user, url: user_path, locale: true do |f| %>
<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>

<div class="field">
  <%= f.label :password %><br>
  <%= f.password_field :password %>
</div>

<div class="field">
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %>
</div>

<div class="field">
  <%= f.submit "sing up"%>
</div>

<%= link_to("ログイン","login_path") %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome</h1>

<p>You are logged in as <strong><%= current_user.email %></strong>.</p>
<%= link_to "ログアウト", logout_path, method: :delete %>